Update 2025-03-16 16:27:28

diff --git a/.github/workflows/Surge.yml b/.github/workflows/Surge.yml
--- a/.github/workflows/Surge.yml
+++ b/.github/workflows/Surge.yml
@@ -1,4 +1,4 @@
-name: 同步 Surge 上游规则
+name: 同步上游规则
 
 on:
   workflow_dispatch:
@@ -17,7 +17,7 @@ jobs:
           repository: thNylHx/Tools
           path: Tools-repo
 
-      - name: 执行脚本
+      - name: 下载 Surge 规则
         run: |
           #!/bin/bash
           repo_name=$(basename "$GITHUB_REPOSITORY")
@@ -343,7 +343,65 @@ jobs:
               echo "$file not found."
             fi
           done
-            
+
+      - name: 下载 mihomo 规则
+        run: |
+          #!/bin/bash
+          repo_name=$(basename "$GITHUB_REPOSITORY")
+          if [[ "$repo_name" == "Tools" ]]; then
+              echo "Running in Tools repository"
+              mkdir -p Tools-repo/Ruleset/mihomo/{geoip,geosite}
+              files=(
+                  # geosite
+                  "geosite/Ads_all.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs"
+                  "geosite/Local.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
+                  "geosite/China.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
+                  "geosite/Openai.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs"
+                  "geosite/PayPal.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"
+                  "geosite/Apple.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"
+                  "geosite/Global.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"
+                  "geosite/Google.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"
+                  "geosite/YouTube.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"
+                  "geosite/Steam.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"
+                  "geosite/Epic.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/epicgames.mrs"
+                  "geosite/Facebook.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.mrs"
+                  "geosite/Instagram.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/instagram.mrs"
+                  "geosite/Twitter.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs"
+                  "geosite/telegram.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"
+                  "geosite/Line.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/line.mrs"
+                  "geosite/GitHub.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"
+                  "geosite/OneDrive.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"
+                  "geosite/Microsoft.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"
+                  "geosite/tiktok.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"
+                  "geosite/Bilibili.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs"
+                  "geosite/Disney.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs"
+                  "geosite/Netflix.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"
+                  "geosite/Spotify.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"
+
+                  # geoip
+                  "geoip/Local.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"
+                  "geoip/China.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
+                  "geoip/Netflix.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"
+                  "geoip/Twitter.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs"
+                  "geoip/telegram.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"
+                  "geoip/Facebook.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs"
+                  "geoip/Google.mrs https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"
+              )
+              for file in "${files[@]}"; do
+                  file_name=$(echo $file | cut -d " " -f 1)
+                  url=$(echo $file | cut -d " " -f 2)
+                  # 确保 URL 格式正确
+                  if [[ ! "$url" =~ ^https?: ]]; then
+                      url="https:$url"
+                  fi
+                  echo "Downloading: $file_name"
+                  curl -f -L "$url" -o "Tools-repo/Ruleset/mihomo/$file_name" || { echo "Download Failed: $url"; exit 1; }
+              done
+          else
+              echo "This is not the Tools repository. Skipping."
+          fi
+        shell: bash
+
       - name: 推送仓库
         run: |
           cd Tools-repo
@@ -371,7 +429,7 @@ jobs:
           message: |
             📢 通知
             🚀 来源：GitHub Actions
-            ✉️ 标题：同步 Surge 上游规则
+            ✉️ 标题：同步上游规则
             📦 仓库：JK567
             ⏰ 时间：${{ env.time }}
             🎉 状态：恭喜你！全部任务执行成功
